export * from "./home/home.component"
export * from "./fetch-data/fetch-data.component"
export * from "./counter/counter.component"
export * from "./register/register.component"
export * from "./login/login.component"
export * from "./calc/calc.component"
