// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinance.Repo;

namespace MyFinance.Repo.Migrations
{
    [DbContext(typeof(MyFinDbContext))]
    partial class MyFinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyFinance.Data.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("BasePercenteges");

                    b.Property<int>("CreditType");

                    b.Property<bool>("IsStarted");

                    b.Property<int>("MonthsCount");

                    b.HasKey("Id");

                    b.ToTable("Credit","MyFin");
                });

            modelBuilder.Entity("MyFinance.Data.MonthPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid?>("CreditId");

                    b.Property<int>("Number");

                    b.Property<decimal>("Payment");

                    b.Property<decimal>("Persentege");

                    b.Property<decimal>("PersentegesPyment");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.ToTable("MonthPayment","MyFin");
                });

            modelBuilder.Entity("MyFinance.Data.SpecialPercentagePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid?>("CreditId");

                    b.Property<int>("MonthCount");

                    b.Property<decimal>("MonthPercentage");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.ToTable("SpecialPercentagePeriod","MyFin");
                });

            modelBuilder.Entity("MyFinance.Data.MonthPayment", b =>
                {
                    b.HasOne("MyFinance.Data.Credit", "Credit")
                        .WithMany("MonthPayments")
                        .HasForeignKey("CreditId");
                });

            modelBuilder.Entity("MyFinance.Data.SpecialPercentagePeriod", b =>
                {
                    b.HasOne("MyFinance.Data.Credit", "Credit")
                        .WithMany("SpecialPersentages")
                        .HasForeignKey("CreditId");
                });
#pragma warning restore 612, 618
        }
    }
}
